### ISSUE TITLE
Reduce current EC2 instance provisioning

### ISSUE THREAD

**Issue by colekettler** [PublicMapping/districtbuilder#1016] opened 2021-09-22 20:26 UTC
We're currently running a hefty number of highly provisioned EC2 instances to keep things stable. We should consider whether we can reduce the number of running instances, move down to less well-provisioned instance types, or both, without significantly sacrificing application reliability or performance.

**Comment by ddohler** [comment] 2021-12-27 19:11
I investigated application metrics with an eye toward reducing our spending on EC2 resources. I had initially planned to try to experimentally determine the application's memory requirements, but after some investigation, I believe that there is enough information available in the AWS console to come up with a plan, so I didn't end up doing any experimentation.

# Context
Our application servers have persistently high memory requirements because they keep information about the geometries for every jurisdiction in memory at all times. In addition, they have transiently even higher memory requirements during startup, because the processing required to load the jurisdiction geometries requires additional memory. Lastly, there are as-yet undiagnosed [issues with application stability under load](https://github.com/PublicMapping/districtbuilder/issues/1015) which require us to maintain a buffer of running application servers in case one or more of them fails.

All of the issues above will require significant engineering investment to resolve, so we've responded in the short-term by provisioning more compute and memory resources. The current state of things is that we host the production site on eight (8) `r5.2xlarge` instances, which is fairly expensive. Our goal is to reduce these costs as much as we can, without impacting application stability, until we can complete the larger engineering efforts that will be required to address the root causes of the problems described above.

Note that there is another source of high infrastructure cost on this project: any pages listing multiple maps (specifically, the Maps and Community Maps pages) have also been a source of increased costs. I didn't investigate strategies for reducing those costs here, but in summary, the situation with those pages is as follows:
- Returning un-simplified map geometries caused the browser to load many megabytes of geometries, which slowed down the page.
- Simplifying map geometries on the fly fixed the issue...until we encountered imperfect state geometries, which caused the simplification library we were using to explode and made the page fail to load if it included any states with corrupt geometries.
- We moved the simplification into the database, which fixed the issue with corrupted geometries, but increased load on the database. This required us to increase the database size to a `t3.large`.
- Separately, we started encountering Postgresql query planner misses on these pages which slowed them down and impacted other application functionality because it increased overall database load. We purchased provisioned IOPS on the database as an immediate recovery response, and suspect that [regularly `REINDEX`ing the `projects` table](https://github.com/PublicMapping/districtbuilder/issues/1086) may provide a permanent fix.

Again, I didn't look into reducing costs from those pages, but am noting them here because we will probably need to address the cost of those pages in order to further reduce costs once we've done all we can do with the application servers.

# Investigation
I looked into two potential approaches for reducing resource usage (and hence cost):
1. Reducing the number of application server instances / servers (we run one task per EC2 instance, so tasks and instances are interchangeable at the moment).
2. Reducing the amount of memory allocated to each application server task, which would allow us to either use a smaller EC2 instance size or pack more of them into a single instance. We know that the baseline memory usage of the app is lower than 32GB, so if the startup usage is also below 32GB, we could potentially drop down to `r5.xlarge` instances, which would roughly halve our hosting costs.

## Number of application tasks
When investigating item 1, I concluded that the current number of tasks (8) provides a sufficient buffer to avoid outages from the stability issues noted in #1015 , but may not provide us with a lot of room to reduce the number of tasks. In this graph of the number of healthy application tasks over the past 6 weeks, you can see that the number rarely dips below 7, but has occasionally dropped to 6 or 5. 
<img width="1241" alt="Screen Shot 2021-12-27 at 1 22 29 PM" src="https://user-images.githubusercontent.com/447977/147497750-10d5805d-c412-41e9-a851-67c8a7a3b542.png">

CPU load per application host also shows a good amount of headroom, remaining in the range of 10-40% CPU utilization.
<img width="1107" alt="Screen Shot 2021-12-27 at 1 22 45 PM" src="https://user-images.githubusercontent.com/447977/147497758-418db663-ce40-4825-918f-ed956d80d4dd.png">

However, it's important to remember that decreasing the number of application tasks will increase the load on the remaining tasks, which may make failures more likely. For example, if we assume that CPU usage is directly proportional to the number of application tasks, we would expect reducing the number of application tasks to 4 to double the load on each task, and might expect to see CPU utilization of 20-80%. That seems fine for the base case, but it looks less fine in cases where 1 or 2 tasks might become unhealthy. That would leave us with only 3 or 2 remaining healthy tasks until the replacement tasks spin up (which takes 20-30 minutes). If those remaining tasks can't handle the load, they might also become unhealthy, which could cause a spiraling outage. I think our best bet here is to slowly decrease the number of application tasks over a period of weeks, checking resource utilization and frequency of task failure each time.

## Memory limit per-task
When looking into item 2, AWS makes [memory utilization metrics](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#service_utilization) available (as distinct from memory **reservation**, which is also available, and which is essentially 100% for us at all times because we allocate one task per host). Here's the maximum memory utilization percentage for the past six weeks on production (I used a period of six hours to smooth out the graph a bit, but because I'm using the Maximum statistic it doesn't change the height of the tallest peaks): 
<img width="1106" alt="Screen Shot 2021-12-27 at 1 21 57 PM" src="https://user-images.githubusercontent.com/447977/147498129-b15cac32-cce3-420c-9e7c-776f73dcae35.png">

We can see that the baseline memory usage is around 47%. Our current memory allocation is 61440 MB, so 47% utilization works out to just under 29GB for the baseline. I remember this number being more like 20GB previously, and I'm not sure what might have caused it to increase. Anyway, there are also peaks to around 57%; I've verified that these correspond with deployments or otherwise launching new application tasks (e.g. to replace one that failed). Therefore, these peaks should be close to the application's startup memory usage. ECS only collects metrics at 1-minute intervals, but during a deploy the maximum statistic will be pulling the maximum usage from across 8 new tasks all booting up at about the same time, so I think there's a good chance that we've captured something close to the true value. There's also one peak all the way up to 61%, which I'm unsure about. 57% of our current memory allocation is is 35GB, and 61% is 37.5GB. Neither of these will fit into a 32GB machine directly, but they're tantalizingly close, so it's possible that running the garbage collector more frequently as memory usage increases will still allow the application to function within 32GB, or that we could tweak something about how we handle application data in order to make it fit.

One thing I noticed in passing is that it appears that all of the existing Fargate infrastructure is still in place. We abandoned Fargate earlier because it has a memory limit of 30GB per task, but the fact that it still exists might allow us to easily experiment with a lower memory limit per task because we could run a parallel set of application tasks on production without impacting the existing production tasks.

# Recommendations
1. Vary the number of application tasks and the resources dedicated to them separately. Changing the number of tasks may change the resources they require, so we shouldn't try to change both at once.
2. Experiment with deploying a parallel production application task using Fargate, limited to 30GB of memory, and see if it becomes healthy. If it does, consider migrating back to Fargate for the application tasks.
3. Slowly reduce the total number of application tasks (perhaps by 1 task per week) while monitoring resource usage and stability.

**Comment by maurizi** [comment] 2022-01-03 13:59
> Experiment with deploying a parallel production application task using Fargate

I don't believe we can switch back to Fargate right now, as we can't set the `vm.max_map_count` parameter we started using in https://github.com/PublicMapping/districtbuilder/pull/942 on Fargate.

**Comment by ddohler** [comment] 2022-01-03 14:15
> I don't believe we can switch back to Fargate right now, as we can't set the vm.max_map_count parameter we started using in #942 on Fargate.

Ah, good point! In that case I think the quickest way to have an impact is to start reducing the number of running application tasks.

To test reducing memory, if we can't use Fargate, it might be helpful to stand up a second EC2-based launch type--that would allow us to test out different resource configurations under production conditions in a safer way because we could still maintain our existing capacity in parallel.

**Comment by ddohler** [comment] 2022-01-04 21:54
Update for archival purposes:
- We decreased the number of active application service tasks from 8 to 6. This went smoothly and has not caused problems so far, but it did surface that the alarm responsible for scaling down the EC2 instances in response to a decrease in the number of application service tasks is [stuck in the alarm state](https://github.com/PublicMapping/districtbuilder/issues/1093).
- We compared the `region_config` tables for both staging and production, and added 11 regions to staging so that it would have a similar memory profile to production. We then attempted to deploy the staging application using `r5.xlarge` instances, which have 32GB of memory. However, this was not successful; the available memory on a 32GB instance did not allow the application to load all of the required data, and it failed during the initialization process. The below graph shows the application churning through service tasks that hit the memory limit and then fail:
<img width="1239" alt="Screen Shot 2022-01-04 at 2 22 50 PM" src="https://user-images.githubusercontent.com/447977/148128193-0778a84d-b96a-49a5-aeb3-922d3a4dea31.png">
There are some additional changes we could make to try to get the application to fit within 32GB, but any success here seems at risk of being only temporary, given that we expect memory usage to continue to grow due to adding new regions. Therefore, our best use of scarce engineering time is probably to invest in a permanent fix for the memory problem, rather than trying to squeeze further memory efficiency out of the current architecture.

For next steps, I'm going to continue monitoring the production application and will try to further reduce the number of service tasks to 5 or 4 without impacting stability, but aside from those potential, incremental improvements, I think we've done about all we can here, so I'm closing this.

**Closed by ddohler** 2022-01-04 21:54 UTC
Labels: operations, actionable backlog

**Comment by ddohler** [comment] 2022-01-05 17:24
Also noting for future reference that I've updated the production `tfvars` with the current value of 6 running service tasks, so production deploys can be safely performed without reverting the reduction in size. I'll return to this once I'm back from leave to try to get it down a bit lower.
