### ISSUE TITLE
Race sidebar charts don't show up in Firefox

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder#256] opened 2020-07-31 20:31 UTC
## Overview 

In Firefox specifically, the race sidebar charts are not being displayed. They show up fine in Chrome and Edge. Here's what it looks like in Firefox:

![screenshot_1](https://user-images.githubusercontent.com/6386/89074848-1fef3600-d34b-11ea-8aea-b93561e5fd9a.png)

## Acceptance criteria

Race sidebar charts are displayed in Firefox

**Comment by tgilcrest** [comment] 2020-08-04 02:17
Duplicate of #243

**Closed by tgilcrest** 2020-08-04 02:17 UTC
Labels: Bug - Medium
