### ISSUE TITLE
Race bar graphs don't show in sidebar on Firefox

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#243] opened 2020-07-31 16:08 UTC
### Description

When using Firefox the race bar graphs in the sidebar do not show up. Hovering over them shows the tooltip correctly.

### Steps To Reproduce

1. Log in to DistrictBuilder on Firefox
2. Go to any map
3. Draw a district (if one doesn't exist)

### Expected behavior

The side bar shows the race demographic bar graphs.

### Actual behavior

The bar graphs do not show up.

### Screenshots

![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/3e0f38b0-3fdd-4f06-ad3a-d209c2e7a2c4)

But the tooltip shows up
![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/119cc761-d640-43eb-8fb9-da940eb94732)

### Your environment

Seen in Windows and Linux Firefox

**Comment by jfrankl** [comment] 2020-08-11 18:56
This appears to be fixed. I suspect it was fixed in #280, but I'm not sure. I cannot reproduce this issue in Firefox 79.

![image](https://user-images.githubusercontent.com/1809908/89937272-da502a00-dbe2-11ea-9f7b-6ec8eafd2a3d.png)

**Closed by jfrankl** 2020-08-11 18:56 UTC
Labels: Bug - Medium, design
