### ISSUE TITLE
Duplicated feature ids causes incorrect geounit selection

### ISSUE THREAD

**Issue by pcaisse** [PublicMapping/districtbuilder#307] opened 2020-08-17 13:24 UTC
## Description
For the DE test data, some tracts have the same feature ids as counties (0, 1, and 2). We're using feature ids to uniquely identify geounits in the app so this causes problems.

The steps to reproduce are specific to DE but this will affect PA or any other region we have data for.

## Steps To Reproduce
1. Using the DE test data, select the entire northernmost county (county 0)
1. Switch to tracts, thus converting the selection to all of the tracts in the county instead of the whole county
1. Save to a district

## Expected behavior
All tracts in county should be assigned to that district

## Actual behavior
Tract 0 is not assigned (this is because of the feature id conflict; when we deselect county 0 we also end up deselecting tract 0 since we use feature id to uniquely identify a geounit but in this case it's duplicated)

## Screenshots
![db_duplicate_feature_id](https://user-images.githubusercontent.com/2926237/90400519-99389980-e06a-11ea-943d-d4fd5696f116.gif)

**Comment by tgilcrest** [comment] 2020-08-17 15:13
I think we should consider using the full FIPS code as the ID for the geounits, since they're designed to be unique, and use the geounit-specifc part as the label shown to the user.

**Comment by tgilcrest** [comment] 2020-08-19 20:11
Duplicate of #315

**Closed** 2020-08-27 18:33 UTC
