### ISSUE TITLE
Unable to covert to 2020 data

### ISSUE THREAD

**Issue by wofchristian** [PublicMapping/districtbuilder#1080] opened 2021-12-02 20:28 UTC
I am trying to covert my map from 2010 to 2020 census data. When I press "Yes, copy to my account", it pops up with "Something went wrong, please try again". This has been going on for the past week.
![districtbuilder issue converting to 2020](https://user-images.githubusercontent.com/66582695/144497885-7b6d0fc4-ca6c-442d-8ba3-c5193bd22414.png)
.

**Comment by maurizi** [comment] 2021-12-17 20:10
After some debugging, it seems this was caused by the crosswalk files for a few states not having the right permissions in S3. I was able to fix this by making everything publicly accessible.

@wofchristian thank you for the reporting this! The problem should be fixed now 🙂

**Closed by maurizi** 2021-12-17 20:10 UTC
