### ISSUE TITLE
Updated values in sidebar revert to original on "Accept"

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#327] opened 2020-08-19 20:48 UTC
## Description
The updated population/demographic values in the sidebar switch back to their original values after the user clicks "Accept"

## Steps To Reproduce

1. Open a project new project
2. Select a county on the map
3. The population of that county should be added to the selected district in the sidebar
4. Click "Accept"

## Expected behavior
I'd expect the updated population for the district to be visible after clicking "Accept"

## Actual behavior
The population for the district reverts back to the original value temporarily. Once the "Accept" process completes, the update value is visible once again.

## Screenshots
https://www.youtube.com/watch?v=TFTykbtAij0

## Your environment

 - OS: macOS
 - Browser: Latest Chrome

## Additional context

After clicking "Accept", the updated value is the important one. Seeing the original value is confusing and it's not the information you want to see.

**Comment by tgilcrest** [comment] 2020-08-29 03:10
Duplicate of #253

**Closed by tgilcrest** 2020-08-29 03:10 UTC
