### ISSUE TITLE
Cannot leave Dane County organization on production

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#713] opened 2021-04-26 20:26 UTC
This from the production logs looks relevant:
![image](https://user-images.githubusercontent.com/4432106/116146190-347b1780-a6ac-11eb-9c04-a453255bcd14.png)

**Comment by tgilcrest** [comment] 2021-04-26 21:16
Duplicate of #714

**Closed by tgilcrest** 2021-04-26 21:16 UTC
