### ISSUE TITLE
Duplicate Map modal from Project Screen does not work

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#932] opened 2021-08-12 21:16 UTC
Steps to reproduce:
 - Create a publicly visible map
 - Log in as a different user, go to the map you made, and click the "Copy this Map" button in the header.

**Comment by maurizi** [comment] 2021-08-12 21:17
https://rollbar.com/Azavea/DistrictBuilder/items/60/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification

**Comment by kevinearldenny** [comment] 2021-08-16 16:22
I'm unable to reproduce this issue locally - seems like it may have been fixed elsewhere. Can we close this?

**Closed** 2021-08-16 16:24 UTC
