### ISSUE TITLE
Update healthcheck with information about regions loaded into memory

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder#254] opened 2020-07-31 20:22 UTC
## Overview

When a new ECS task comes up, it first needs to load all region data into memory before we being routing traffic to it. Therefore, we need to update the health check to contain information about the status of regions loaded into memory, so it can be successfully marked as healthy.

## Acceptance criteria

The healthcheck endpoint provides enough information that we are able to determine the service has loaded all relevant region data into memory.

**Comment by hectcastro** [comment] 2020-08-05 15:17
This may end up being a duplicate of https://github.com/PublicMapping/districtbuilder/issues/251. Feel free to close 251.

**Closed** 2020-08-28 17:14 UTC
