### ISSUE TITLE
Route to login when logged out

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#350] opened 2020-08-27 01:31 UTC
## Detailed Description
When a user is logged out, they see a mostly empty page with login and registration links in the header. We should automatically direct a user to the login screen.

## Context
When a user lands on the app and are logged out, we can assume they want to log in. Let's automatically route them to the login.

**Comment by maurizi** [comment] 2020-08-27 13:43
Duplicate of https://github.com/PublicMapping/districtbuilder/issues/296

**Closed by maurizi** 2020-08-27 13:43 UTC
